### ISSUE TITLE
kafka-net-core nuget

### ISSUE THREAD

**Issue by PeksiV** [snmslavk/kafka-net-core#3]
Provided kafka-net-core nuget package contains debug binaries?

**Comment by snmslavk** [comment]
No, it doesn't have debug information

**Comment by snmslavk** [comment]
I published new version just to be sure. It's definitely in release now.

https://www.nuget.org/packages/kafka-net-core/1.0.3
You can check after it will be published and listed

**Comment by PeksiV** [comment]
Tested with 1.0.3 version and it works!
