### ISSUE TITLE
Libraires should use netstandard not netcoreapp

### ISSUE THREAD

**Issue by tommed** [snmslavk/kafka-net-core#4]
Please change this library from targeting netcoreapp to netstandard.
All libraries should be using netstandard for portability.

**Comment by snmslavk** [comment]
Hi,

Actually it's a good point, I was thinking about it and have heard it from other guys. So may be soon I'll do it.

**Comment by tommed** [comment]
I have created a pull request; there's a TODO comment I've added as the build generates a warning from existing code about a non-awaited task.

https://github.com/snmslavk/kafka-net-core/pull/5

**Comment by snmslavk** [comment]
Solved
