### ISSUE TITLE
When getting ProduceResponses, how to know which ProduceResponse corresponds to which Message sent?

### ISSUE THREAD

**Issue by SwissMaWi** [snmslavk/kafka-net-core#6]
Hi there.
I am using your library, great work btw.
Now when using producer.SendMessageAsync I am getting a list of ProduceResponse.
How can I match them to the list of messages I sent originally?
Regards, Martin

**Comment by SwissMaWi** [comment]
I see there is only one response per call... so this is obsolete. You can delete my issue.

**Comment by snmslavk** [comment]
No problem, thanks for using it
